stages:
  - deploy


deploy-job:
  stage: deploy
  only:
      - main
  when: manual
  script:
    - echo "Deploying application..."
    - git -C /home/project/event-scheduler pull
    - docker-compose -f /home/project/event-scheduler/docker-compose.yml build
    - docker-compose -f /home/project/event-scheduler/docker-compose.yml restart
    - echo "Application successfully deployed."
