version: '3.7'

volumes:
  db_data:


services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:14.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8088:8080
